### ISSUE TITLE
MonthPicker styling

### ISSUE THREAD

**Issue by Sub-Zero-1** [mgcrea/react-native-propel-kit#1]
Hi!
Is there a way to modify the appearance of the monthPicker? The buttons are green and I would need to change them to e.g. red?
I tried to use style but without effect.

**Comment by mgcrea** [comment]
Just released a `v0.8.7` release with the proper exports.

Since the <ModalDialogButton /> is quite deep in the tree, you can't pass a prop to style it, however you can easily override styles defaults once accross your app:

In a file like `defaults.js` imported from your `index.js`
```js
import {modalDialogButtonDefaultStyles} from '@mgcrea/react-native-modal-dialog';

Object.assign(modalDialogButtonDefaultStyles, {
  text: {
    ...modalDialogButtonDefaultStyles.text,
    color: '#E91E63',
  },
});
```

eg:
<img width="501" alt="Screenshot 2020-04-22 at 19 36 03" src="https://user-images.githubusercontent.com/108273/80014376-81904080-84d0-11ea-9a82-a111cf032585.png">
